### ISSUE TITLE
Add readme with descriptions

### ISSUE THREAD

**Issue by dufferzafar** [trygveaa/kitty-kitten-search#1]
Hi, could you please add a readme with description what each kitten does / how you use it? Especially the search kitten, looks like something cool, thanks!

**Comment by trygveaa** [comment]
It's still in an early stage, and won't work the way I want until https://github.com/kovidgoyal/kitty/issues/2391 is fixed.

That said, it is usable, you can see a demonstration of it in that issue. I can add a readme with description, but the short version is to place the two files in this repo in the same directory as kitty.conf and add this mapping to a key in kitty.conf:

```
launch --allow-remote-control kitty +kitten search.py @active-kitty-window-id
```

`search.py` is the main kitten. `scroll_mark.py` is just needed because of a limitation in the remote protocol, and is used by `search.py`.
